;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage",DevComment="Damage magnitude used by SetByCaller GameplayEffects.")
+GameplayTagList=(Tag="GameplayCue.Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Impact.Concrete",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Impact.Default",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Impact.Glass",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Impact.Metal",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Weapon.Impact.Wood",DevComment="")
+GameplayTagList=(Tag="State.Death",DevComment="")
+GameplayTagList=(Tag="State.Weapon.Reloading",DevComment="")

